[package]
name = "lieui"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.10.0"
color = "0.3"
euclid = "0.22"
parley = "0.7"
quick-xml = { version = "0.38.4", features = [ "serialize" ] }
serde = { version = "1.0", features = [ "derive" ] }
slotmap = "1.0.7"
softbuffer = "0.4.6"
taffy = { version = "0.9", features = [ "serde" ] }
thiserror = "1"
vello_cpu = { version ="0.0.4", features = [] }
winit = "0.30"

[dev-dependencies]
